added changes to geoschem_run_scripts and updated variable names that changed in local cluster updates

diff --git a/src/geoschem_run_scripts/ch4_run.template b/src/geoschem_run_scripts/ch4_run.template
--- a/src/geoschem_run_scripts/ch4_run.template
+++ b/src/geoschem_run_scripts/ch4_run.template
@@ -19,13 +19,21 @@ id=namename
 # Define GEOS-Chem log file
 log="$id.log"
 
+# remove error status file if present
+rm -f .error_status_file.txt
+
 #-------------------------------------------------
 # Start the simulation
 #-------------------------------------------------
 # Run GEOS-Chem and pipe output to log
 ./gcclassic >> $log
 
-# Echo end fin
+retVal=$?
+if [ $retVal -ne 0 ]; then
+    echo "Error Status: $retVal" > .error_status_file.txt
+    exit $retVal
+fi
+
 echo '===> Run ended at' `date` >> $log
 
 #-------------------------------------------------
